Feature/validation
RoboQuasar/WebInteractive-admin pull request #12
Opened 2021-03-10 21:33 UTC by Atemy

Вроде бы сделал нормальную логику, но вот с подсказкой и полем подсказки у меня большая беда((

2021-03-15 20:16 UTC, Atemy commented
Не смог красиво оформить чятик тултипа,
Вроде вся валидация и сообщения выполняются правильно, но буду рад замечаниям!
пока что сделанно только окно регистрации, но я вложил в него печень и душу =)

2021-03-16 11:52 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +    console.log(e.target.value);
вот эти логи в финальном коде старайся удалять :)

2021-03-16 12:15 UTC, RoboQuasar requested changes

2021-03-16 12:15 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +    console.log(e.target.value);
и вот эти

2021-03-16 12:15 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +    setButtonMessage("Загрузка..");
О, вот это интересный подход, вроде хороший, но обычно в практике стейт делают именно isLoading и потом текст кнопки уже переключают именно в JSX типо 
```{ isLoading ? "Загрузка..." : "Войти"  }``` через тернарный оператор

2021-03-16 12:15 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +    setButtonMessage("Войти");
вот видишь у тебя это ```setButtonMessage("Войти");``` 3 раза повторяется, у конструкции ```try {} ... catch () {} ...``` есть ещё третья часть ```finally {}```, туда можно писать код, который в любом случае должен выполниться, вот как раз это ```setButtonMessage("Войти");``` туда можно написать

2021-03-16 12:15 UTC, RoboQuasar commented on src/components/Question/index.jsx
> +  children: PropTypes.node,
похоже это лишний пропс тут

2021-03-16 12:15 UTC, RoboQuasar commented on src/components/Question/index.jsx
> +      <QuestionMark className={`${styles.question} ${props.questClass}`}id={props.id}/>
тут нужен пробел перед id

2021-03-16 12:15 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
>            <NavigationLink className={styles.registration} hrefLink="/registration">Регистрация</NavigationLink>
![image](https://user-images.githubusercontent.com/20340783/111306308-1bbd2200-8669-11eb-8bac-052df3ae22be.png)

чет эта ссылка некрасивая при Ховере ((

2021-03-16 12:15 UTC, RoboQuasar commented on src/components/RegistrationWindow/index.jsx
> +        setErrorMessage("Как много пустоты: не протолкнуться. Пожалуйста, заполните все поля");
🤣🤣🤣

2021-03-16 12:15 UTC, RoboQuasar commented on src/components/RegistrationWindow/index.jsx
> +        return result.json();
тут вот на данном этапе всё же надо добавить else {}, чтоб возвращался result.json(); только в случае НЕ успеха

2021-03-16 12:15 UTC, RoboQuasar commented on src/components/RegistrationWindow/styles.module.scss
> +  // .hint:hover::after{
вот тут ты реально красавчек))) Так и будем делать)

2021-03-20 11:48 UTC, Atemy commented on src/components/RegistrationWindow/index.jsx
> +        return result.json();
![image](https://user-images.githubusercontent.com/22544254/111868482-263e2b00-898b-11eb-80dc-8ce2f31add78.png)
![image](https://user-images.githubusercontent.com/22544254/111868486-28a08500-898b-11eb-9176-f4be1b8869a2.png)
Если я не обрабатываю result.json, то все крашится(

2021-03-20 11:50 UTC, Atemy commented on src/components/RegistrationWindow/index.jsx
> +        return result.json();
закоментил Else. может я просто не правильно тебя понял

2021-03-20 12:37 UTC, Atemy commented on src/components/AuthWindow/index.jsx
> +    setButtonMessage("Загрузка..");
Сделал и на регистрации и на аутенфикации

2021-03-20 12:44 UTC, Atemy commented on src/components/AuthWindow/index.jsx
>            <NavigationLink className={styles.registration} hrefLink="/registration">Регистрация</NavigationLink>
Теперь она как я =)

2021-03-25 14:25 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +    console.log(e.target.value);
ээээх, эти логи надо бы поудалять

2021-03-25 14:25 UTC, RoboQuasar commented on src/components/AuthWindow/styles.module.scss
>          & .enterButton{
У этой кнопочки забыл `cursor: pointer`

2021-03-25 14:25 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +          <button className={styles.enterButton}>{ isLoading ? "Загрузка..." : "Войти" } </button>
И добавь плиз сюда тоже disabled и проверку на заполненность полей логина и пароля, хотя б по 2 символа.
А то сейчас можно отправлять вообще с обоими пустыми полями (

2021-03-25 14:25 UTC, RoboQuasar commented on src/components/RegistrationWindow/index.jsx
> +    if(name.length < 2){
вот тут вот есть проблема
![image](https://user-images.githubusercontent.com/20340783/112487220-9c78ce00-8d8d-11eb-8446-75c21d405cbd.png)

2021-03-25 14:25 UTC, RoboQuasar commented on src/components/RegistrationWindow/index.jsx
> +    if(name.length < 2){
Если Фамилия Совсем не заполнена, то её просто нет и быть не обязательна.
Но если человек Фамилию всё-таки начал заполнять, то она должна быть длиннее 2х символов

2021-03-25 14:25 UTC, RoboQuasar commented on src/components/RegistrationWindow/index.jsx
> +            <button  className={styles.enterButton} >{ isLoading ? "Загрузка..." : "Войти" }</button>
Воу, а тут как так снова стало "Войти", забыл ты, видимо изменить после копирования, вставления

2021-03-25 14:25 UTC, RoboQuasar commented on src/components/RegistrationWindow/index.jsx
> +        return result.json();
![image](https://user-images.githubusercontent.com/20340783/112489008-1a89a480-8d8f-11eb-986e-087e2e404824.png)

2021-03-27 12:02 UTC, Atemy commented on src/components/AuthWindow/styles.module.scss
>          & .enterButton{
Сделал и на входе и на регистрации. еще добавил рамку при наведении.

2021-03-27 14:08 UTC, Atemy commented on src/components/RegistrationWindow/index.jsx
> +        return result.json();
spasiba!

2021-03-29 12:48 UTC, RoboQuasar approved these changes

2021-04-26 21:08 UTC, merged