Left Menu
RoboQuasar/WebInteractive-admin pull request #3
Opened 2020-12-06 16:23 UTC by Atemy

2020-12-06 20:05 UTC, RoboQuasar commented on src/containers/App/index.jsx
> +ergsdgbsg;
хех

2020-12-08 12:15 UTC, RoboQuasar requested changes

2020-12-08 12:15 UTC, RoboQuasar commented on src/components/NavMenu.jsx
> +
это лишняя строка

2020-12-08 12:15 UTC, RoboQuasar commented on src/components/NavMenu.jsx
> +
и это лишняя

2020-12-08 12:15 UTC, RoboQuasar commented on src/components/NavMenu.jsx
> +                <Nav_Button >Виджеты</Nav_Button>
Тут пробел лишний, надо `<Nav_Button>` - без пробелов

2020-12-08 12:15 UTC, RoboQuasar commented on src/components/NavMenu.jsx
> +        <div className={styles.navMenu}>
И это по html структуре всё же список элементов, попробуй заменить на конструкцию `<ul>, <li>`

2020-12-08 12:15 UTC, RoboQuasar commented on src/components/NavMenu.jsx
> +            <div className={styles.bottomNav}>
И вот вместо группировки через div-ы, можно попробовать прокинуть класс как пропс или сделать вспомогательный пропс просто

2020-12-08 12:15 UTC, RoboQuasar commented on src/components/NavMenu.jsx
> +                <Nav_Button >Анимации</Nav_Button>
В React принято компоненты именовать через CamelCase, а не Snake_case, то есть надо именно NavButton

2020-12-08 12:15 UTC, RoboQuasar commented on src/components/Nav_Button.jsx
> +        <div className={styles.navButton}>
ой ёй ёй, ты что-то совсем html подзабыл? А где теги вообще, кроме div?

2020-12-08 12:15 UTC, RoboQuasar commented on src/components/NavMenu.jsx
> +import Nav_Button from './Nav_Button.jsx';
На самом деле есть такое правило: Если это ссылка - называй `SomethingLink`, а если кнопка `SomethingButton`, а  в данном случае у тебя в левом меню это список ссылок именно

2020-12-08 12:15 UTC, RoboQuasar commented on src/components/NavMenu.jsx
> +export default NavMenu;
ещё вот видишь в конце строки круг красный? Это Гитовая фишка, надо одну пустую строку в конце файла оставлять что Гит понял где конец файла

2020-12-08 12:15 UTC, RoboQuasar commented on src/components/Nav_Button.jsx
> +function NavButton(props) {
ну и вот тут у тебя компонент хорошо называется, почему же используется как snake_case?

2020-12-08 12:15 UTC, RoboQuasar commented on src/containers/App/index.jsx
> +            <NavMenu />
и вот это твоё меню надо бы уже внутрь странички положить, в файл `pages/MainPage/index.jsx`

2020-12-08 12:15 UTC, RoboQuasar commented on src/styles/navMenu.module.scss
> +
тут очень много лишних строк

2020-12-08 12:15 UTC, RoboQuasar commented on src/styles/css-vars.scss
> +$leftMenuBackgroundColor: #F7F6FF;
старайся сразу смотреть есть ли где-то ещё в проекте такой же цвет, вот этот будет ещё и в правом меню, значит название уже не универсально

2020-12-08 12:15 UTC, RoboQuasar commented on src/containers/App/styles.module.scss
> +  //padding: 10px;
а тут коммент зачем такой?

2020-12-08 12:15 UTC, RoboQuasar commented on src/containers/App/styles.module.scss
> +.main2{
а этот класс вроде не нужен

2020-12-08 12:15 UTC, RoboQuasar commented on src/styles/css-vars.scss
> +$buttonStyle: #979BFF;
вот это название переменной тоже смысла не передаёт, кнопок в проекте будет много потом, надо бы конкретизировать

2020-12-08 12:15 UTC, RoboQuasar commented on src/styles/navMenu.module.scss
> +        height: 30%;
вот всё же пока что стоит избегать высоты в процентах, лучше высоту вообще не указывать фиксировано в данном случае

2020-12-08 12:15 UTC, RoboQuasar commented on src/styles/navMenu.module.scss
> +        display: flex;
тут конечно flex лишнее, это ж текстовый элемент, можно написать
```
text-align: center;
vertical-align: middle;
```
и если по вертикали не сработает, то задать `line-height: 40px;`

2020-12-08 12:15 UTC, RoboQuasar commented on src/styles/navMenu.module.scss
> +        display: flex;
и тут флексы лишние, так как можно просто элементы положить, задать им display: block; и они будут просто по вертикали вставать

2020-12-10 18:23 UTC, Atemy commented on src/components/NavMenu.jsx
> +
+

2020-12-10 18:23 UTC, Atemy commented on src/components/NavMenu.jsx
> +
+

2020-12-10 18:24 UTC, Atemy commented on src/components/NavMenu.jsx
> +                <Nav_Button >Виджеты</Nav_Button>
+

2020-12-10 18:44 UTC, Atemy commented on src/components/NavMenu.jsx
> +                <Nav_Button >Анимации</Nav_Button>
+

2020-12-10 18:46 UTC, Atemy commented on src/containers/App/styles.module.scss
> +  //padding: 10px;
+

2020-12-10 18:47 UTC, Atemy commented on src/containers/App/styles.module.scss
> +.main2{
+

2020-12-18 09:07 UTC, RoboQuasar commented on src/components/LeftMenu/LeftMenu.module.scss
> +    }
стили, общие для всех тегов (обнуление отступов или list-style-type: none;), лучше выносить в общий файл global.css. А вот тут оставить именно нацеливание по классу и с конкретными стилями (вот если конкретный отступ циферкой)

2020-12-18 09:09 UTC, RoboQuasar commented on src/components/LeftMenu/index.jsx
> +//Мне не нравится как тут прописан путь, но по другому компонент не видет файл стилей.
`import styles from './LeftMenu.module.scss';` а вот так не сработает разве?

2020-12-18 09:10 UTC, RoboQuasar commented on src/components/LeftMenu/index.jsx
> +        <div className={styles.navMenu}>
вот этот `<div>` всё ещё лишний, можно сразу писать `<ul>` прям.
И проверь структуру html, у тебя получилось ul -> a -> li, а должно быть ul -> li -> a

2020-12-18 09:13 UTC, RoboQuasar commented on src/components/LeftMenu/index.jsx
> +        <div className={styles.navMenu}>
Из-за этого стили могут ломаться. Нельзя ставить блочные элементы внутри строчных. тег a - строчный, а li блочный

2020-12-18 09:13 UTC, RoboQuasar commented on src/components/NavLink/NavLink.module.scss
> +        color: red;
красный текст? Вроде не было такого в макетах ((

2020-12-18 09:15 UTC, RoboQuasar commented on src/components/NavLink/index.jsx
> +            {/* я так понимаю, этому компоненту нужно придать какой либо дефолтный стиль, а в LeftMenu уже менять его?*/}
В идеале NavLink будет самый внутренний и да, ему нужен дефолтный стиль

2020-12-18 10:02 UTC, RoboQuasar commented on src/components/LeftMenu/index.jsx
> +        <div className={styles.navMenu}>
![WhatsApp Image 2020-12-18 at 12 41 10](https://user-images.githubusercontent.com/20340783/102601498-4c0c2780-4131-11eb-955a-897c8d236d62.jpeg)
![WhatsApp Image 2020-12-18 at 12 46 20](https://user-images.githubusercontent.com/20340783/102601502-4d3d5480-4131-11eb-89e7-dfd43572fb34.jpeg)
![image](https://user-images.githubusercontent.com/20340783/102601600-72ca5e00-4131-11eb-90b2-ed1908dc54fc.png)

2020-12-18 10:27 UTC, RoboQuasar commented on src/components/LeftMenu/LeftMenu.module.scss
> +    li:hover{
И вот этот :hover эффект лучше будет перенести на саму ссылку, а не на li элемент

2020-12-22 09:26 UTC, merged