[WIADMIN-12]
RoboQuasar/WebInteractive-admin pull request #6
Opened 2021-01-18 19:15 UTC by Atemy

2021-01-19 08:48 UTC, RoboQuasar commented on src/components/AuthModalWindow/index.jsx
> +const AuthModalWindow = () => {
Это у нас всё же будет страничка, поэтому лучше не в `components` её положить, а сразу в `pages`

2021-01-19 08:49 UTC, RoboQuasar commented on src/components/LeftMenu/LeftMenu.module.scss
> +<<<<<<< HEAD
вот тут, у тебя локально скорее всего исправлено уже, видишь, закоммитился конфликт

2021-01-19 08:50 UTC, RoboQuasar commented on src/components/LogoutIcon/index.jsx
> +import {ReactComponent as WebInteractiveUserIcon} from 'icons/logout icon.svg';
`logout icon.svg` старайся всё же без пробелов названия файликов писать, могут быть проблемасы при работе через консоль с такими названиями

2021-01-19 08:51 UTC, RoboQuasar commented on src/components/LogoutIcon/index.jsx
> +const LogoutIcon = () => {
Ии, как мы на созвончике обсуждали, сделай плиз красивенько иконку эту, ну и плюс у тебя должно было сохраниться то как мы основное лого поправили без дива

2021-01-19 08:52 UTC, RoboQuasar commented on src/components/ModalWindow/index.jsx
> +      {/* Почему то не могу подхватить children.classname дочерним компонентом */}
ну судя по комменту, надо не `classname`, а `className`, большая буква имеет значение

2021-01-19 08:53 UTC, RoboQuasar commented on src/components/ModalWindow/styles.module.scss
> +.ModalArea {
и вот да, в данном случае это будет не модальное окно, а просто страничка, но сам компонент модалки можешь оставить, пригодится для формы смены пароля

2021-01-19 08:54 UTC, RoboQuasar commented on src/components/ModalWindow/styles.module.scss
> +   .ModalWindow{
вот тут почитай всё же что такое амперсант (знак &) в SCSS (на самом деле это ссылка на родительский селектор, но лучше примерчики посмотреть) и чего он делает, лучше писать селектор 
``` & .ModalWindow{ ```

2021-01-19 08:58 UTC, RoboQuasar commented on src/components/RightLogBar/index.jsx
> +//Какие дочерние компоненты принимает эта функция?
ну вот так как у тебя написано, она не принимает никаких дочерних компонентов и это вполне нормально))

Плюс над названиями всё же можно подумать ещё, тут скорее всего просто `RightSideBar` или `RightBar` или `RightSide`, ну или если тебе хотелось очень в название вставить Логин, то лучше всё же полностью писать, типо `LoginBar`, `LoginLogoutRightBar` - слишком длинно, но легко читается или `AuthRightBar` - более универсально

2021-01-19 09:00 UTC, RoboQuasar commented on src/components/RightLogBar/index.jsx
> +//Какие дочерние компоненты принимает эта функция?
Но вообще в принципе часть слова `Log`  обычно относится к логированию) типо `console.log` Поэтому `RightLogBar ` мне с первого взгляда показалось что эта штука что-то логирует, записывает, следит

2021-01-19 09:01 UTC, RoboQuasar commented on src/components/RightLogBar/styles.module.scss
> +.rightLogBar {
В стилях можешь, первое время следить за порядком стилей, вот по этому гайду https://codeguide.academy/html-css.html#css-order

2021-01-19 09:01 UTC, RoboQuasar commented on src/components/RightLogBar/styles.module.scss
> +.rightLogBar {
Так гораздо проще понимать и запоминать какие стили за что отвечают

2021-01-19 09:10 UTC, RoboQuasar commented on src/icons/logout icon.svg
> +<svg width="35" height="40" viewBox="0 0 35 40" fill="none" xmlns="http://www.w3.org/2000/svg">
вот примерчик накидал
https://codepen.io/RoboQuasar/pen/yLawBVY

2021-01-19 09:11 UTC, RoboQuasar commented
И не забудь закоммитить изменения которые ещё на созвоне сделал по исправлению ошибок и возвращению того что где-то пропало

2021-01-20 17:32 UTC, Atemy commented on src/components/ModalWindow/index.jsx
> +      {/* Почему то не могу подхватить children.classname дочерним компонентом */}
там было все правильно, опечатка именно в комменте(

2021-01-20 17:33 UTC, Atemy commented on src/components/LogoutIcon/index.jsx
> +const LogoutIcon = () => {
![image](https://user-images.githubusercontent.com/22544254/105212529-a2b8b700-5b5e-11eb-800f-36ba16a4b7bf.png)
Не понимаю откуда у тега <a> появляется высота 61px(

2021-01-25 09:17 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +     <label htmlFor="email">Логин</label> <input type="email" /><br />
вот тут если добавил аттрибут `htmlFor` , то надо ж и `id` добавить соответствующий к input-у

2021-01-25 09:24 UTC, RoboQuasar requested changes

2021-01-25 09:24 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +     <input type="submit" value="войти"/>
Тут, насколько мне известно, `<input type="submit"` уже довольно устаревшее использование, лучше использовать `button` ,  вот тут можно вкратце почитать
https://ru.stackoverflow.com/questions/727902/button-%D0%B8%D0%BB%D0%B8-input

2021-01-25 09:24 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +  children: PropTypes.node,
И тут нет смысла прописывать Типы пропсов, если сами эти пропсы в компоненте не используются, вот например у тебя тут нет использования `children` в компоненте

2021-01-25 09:24 UTC, RoboQuasar commented on src/components/LogoutIcon/index.jsx
> +const LogoutIcon = () => {
Хм, вообще надо детальнее посмотреть, но похоже что у нас задано `height: 100%;` у этой ссылки

2021-01-25 09:24 UTC, RoboQuasar commented on src/styles/css-vars.scss
> +  --pochtibeliy: #FCF8FF;
ахахаха ><

2021-01-27 17:11 UTC, Atemy commented on src/styles/css-vars.scss
> +  --pochtibeliy: #FCF8FF;
я забыл сайт который называет цвета по коду(

2021-01-27 17:28 UTC, Atemy commented on src/components/LogoutIcon/index.jsx
> +const LogoutIcon = () => {
Да, убрал у ссылки height 100% и поправил у li line-heigth с 1.15 на 1

2021-02-02 04:24 UTC, merged