Верста окна входа
RoboQuasar/WebInteractive-admin pull request #9
Opened 2021-02-13 16:55 UTC by Atemy

2021-02-13 18:48 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +        <p className={styles.greetingText}>Добро пожаловать<br />в систему оживления сайтов!</p>
Тут прямо можно использовать лучше h1 или h2 тег - заголовок странички целой всё-таки

2021-02-13 18:50 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +        <div className={styles.wrapInput}>
тут вообще можно было чуть меньше тегов использовать, например 
```
<label htmlFor="email" className={styles.labelText}>
  Логин
  <input type="email" className={styles.inputField}/>
</label>
```
Но можно и так оставить, вполне сойдёт

2021-02-13 19:07 UTC, RoboQuasar commented on src/components/AuthWindow/styles.module.scss
> +    vertical-align: middle;
Этот стиль тут лишний

2021-02-13 19:08 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +    <section className={styles.pageLayout}>
Надо бы другой какой-нибудь тег использовать, в ДОМ-дереве получается беда

2021-02-13 19:09 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +    <section className={styles.pageLayout}>
![image](https://user-images.githubusercontent.com/20340783/107859029-11302280-6e48-11eb-84cd-efc078ecdedf.png)

2021-02-13 19:10 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +          <input type="email" className={styles.inputField}/>
Всё же нужен id для input? Смотри, input и label надо связать друг с другом, если жмёшь на label и input не реагирует, значит ошибка

2021-02-13 19:11 UTC, RoboQuasar commented on src/components/AuthWindow/styles.module.scss
> +      width: 725px;
Ширину фиксированную надо бы убрать.
Или добавить box-sizing: border-box;

2021-02-13 19:12 UTC, RoboQuasar commented on src/components/AuthWindow/styles.module.scss
> +      text-align: center;
Это ж лишний стиль

2021-02-13 19:13 UTC, RoboQuasar commented on src/components/AuthWindow/styles.module.scss
> +      width: 423px;
вроде слишком большая ширина

2021-02-13 19:15 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +          <input type="password" className={styles.inputField}/>
![image](https://user-images.githubusercontent.com/20340783/107859198-e6929980-6e48-11eb-9765-733e8be3d132.png)
 Тут вот стили шрифта тоже нужны, вот на картинке пример

2021-02-13 19:16 UTC, RoboQuasar commented on src/components/AuthWindow/styles.module.scss
> +      font-family: Roboto;
Этот стиль шрифт на сайт сейчас не подключен, я задачку отдельную создал по подключению стилей

2021-02-13 19:18 UTC, RoboQuasar commented on src/components/AuthWindow/styles.module.scss
> +    justify-content: center;
Если у формы внутри есть стиль margin: auto; то эта строка уже не нужна

2021-02-13 19:54 UTC, Atemy commented on src/components/AuthWindow/index.jsx
> +          <input type="email" className={styles.inputField}/>
Спасибо что напомнил(( мой косяк

2021-02-15 15:34 UTC, Atemy commented on src/components/AuthWindow/index.jsx
> +        <div className={styles.wrapInput}>
всмысле без дивов?

2021-02-15 15:38 UTC, Atemy commented on src/components/AuthWindow/index.jsx
> +    <section className={styles.pageLayout}>
например див?)

2021-02-15 15:43 UTC, Atemy commented on src/components/AuthWindow/styles.module.scss
> +      width: 725px;
добавил box-sizing: border-box;

2021-02-15 15:45 UTC, Atemy commented on src/components/AuthWindow/styles.module.scss
> +      text-align: center;
Точно? наверное вместо него должно быть что то другое?
![image](https://user-images.githubusercontent.com/22544254/107967311-01d2e580-6fbe-11eb-991e-b40fa1ca4f2f.png)
![image](https://user-images.githubusercontent.com/22544254/107967339-09928a00-6fbe-11eb-938e-95a8e89dfc58.png)

2021-02-15 15:48 UTC, Atemy commented on src/components/AuthWindow/styles.module.scss
> +      width: 423px;
да, она больше чем надо, брал за ориентир заголовок и хотел довести до ума поле ввода с помощью маргинов
![image](https://user-images.githubusercontent.com/22544254/107967571-58d8ba80-6fbe-11eb-9e61-921bcb19a472.png)

2021-02-15 17:53 UTC, Atemy reviewed
Исправлены ошибки, доверстанны ссылки и кнопки

2021-02-16 09:50 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +        <div className={styles.wrapInput}>
Да, без дивов

2021-02-16 09:51 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +    <section className={styles.pageLayout}>
Да,  можно вполне и div

2021-02-16 09:52 UTC, RoboQuasar commented on src/components/AuthWindow/styles.module.scss
> +      text-align: center;
О, выглядит логично, может мне показалось что этот text-align к чему-то другому относится (
Значит окейно

2021-02-16 10:03 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +          <label id="emailField" htmlFor="email" className={styles.labelText}>Логин</label>
Эээхххх, почитай плиз всё же как связывать label и input, у label `htmlFor` должен совпадать с id input-а

2021-02-16 10:04 UTC, RoboQuasar commented on src/components/AuthWindow/index.jsx
> +          <label id="emailField" htmlFor="email" className={styles.labelText}>Логин</label>
А у самого label id не нужен

2021-02-20 19:24 UTC, RoboQuasar commented on src/styles/fonts.scss
> +@font-face{
Вот тут ты подключил только `"fonts/Roboto-Black.`

2021-02-20 19:28 UTC, RoboQuasar commented on src/styles/fonts.scss
> +@font-face{
![image](https://user-images.githubusercontent.com/20340783/108606385-e48d8500-73ca-11eb-8bef-cb50792b46bc.png)

2021-02-20 19:30 UTC, RoboQuasar requested changes

2021-02-20 19:30 UTC, RoboQuasar commented on src/styles/fonts.scss
> +@font-face{
Вот так правильно. Тут ты пишешь какой файл браузеру надо будет подключить при указании font-weight.
Тут получится font-weight: bold -> подключится файл "fonts/Roboto-Black.woff2"
И по такому принципу надо будет подключить все виды файлов, отдельно Light, Black, Medium, Bold, Italic.
Вот как раз получится 6 свойств @font-face.

2021-02-21 12:05 UTC, merged